---
- name: Health check 
  hosts: switches, routers
  gather_facts: no

  vars_files:
  - files/commands.yaml  
  - vars/common.yaml
  
  tasks:
 
  - name: Get the facts
    ios_facts:
      gather_subset: all

########### include tasks ###################

  - name: Check and return check_result 
    # [0 => router, 1 => switch, 2 => nexus ]
    vars:
      hc_commands: "{%- if ('switches' in group_names) -%}
                        {{ healthcheck_commands[1].switch }}          
                    {%- elif ('routers' in group_names) -%}
                        {{ healthcheck_commands[0].router }}
                    {%- endif -%}"
    include_tasks: "sub-tasks/devices.yml"


  - name: Build csv content line 
    set_fact:
      csv_line: "{{ check_result | join('\",\"') }}"
  
  #- name: Create CSV file
  #  lineinfile:
  #    dest: "{{ csv_path }}"                    
  #    line: " {{ csv_header }}"
  #    create: yes
  #    state: present

  #- name: CSV - Blank lines removal
  #  lineinfile:
  #    path: " {{ csv_path }}"
  #    state: absent
  #    regex: '^\s*$'

###########Write to CSV#####################
  - name: CSV - Write information into .csv file
    lineinfile:
      dest: "/home/ec2-user/{{ csv_path }}"
      line: "\"{{ansible_ssh_host}}\",\"{{ csv_line }}\""
    deligate_to: localhost  
 
